/* soapServer.c
   Generated by gSOAP 2.8.44 for tr069.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.44 2017-03-11 09:23:32 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Inform"))
		return soap_serve_cwmp__Inform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterValues"))
		return soap_serve_cwmp__GetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Reboot"))
		return soap_serve_cwmp__Reboot(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap *soap)
{	struct cwmp__Inform soap_tmp_cwmp__Inform;
	struct cwmp__InformResponse response;
	soap_default_cwmp__InformResponse(soap, &response);
	soap_default_cwmp__Inform(soap, &soap_tmp_cwmp__Inform);
	if (!soap_get_cwmp__Inform(soap, &soap_tmp_cwmp__Inform, "cwmp:Inform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Inform(soap, soap_tmp_cwmp__Inform.DeviceId, soap_tmp_cwmp__Inform.Event, soap_tmp_cwmp__Inform.MaxEnvelopes, soap_tmp_cwmp__Inform.CurrentTime, soap_tmp_cwmp__Inform.RetryCount, soap_tmp_cwmp__Inform.ParameterList, &response);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_cwmp__InformResponse(soap, &response);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__InformResponse(soap, &response, "cwmp:InformResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__InformResponse(soap, &response, "cwmp:InformResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterValues(struct soap *soap)
{	struct cwmp__GetParameterValues soap_tmp_cwmp__GetParameterValues;
	struct cwmp__GetParameterValuesResponse soap_tmp_cwmp__GetParameterValuesResponse;
	struct ParameterValueList soap_tmp_ParameterValueList;
	soap_default_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse);
	soap_default_ParameterValueList(soap, &soap_tmp_ParameterValueList);
	soap_tmp_cwmp__GetParameterValuesResponse.ParameterList = &soap_tmp_ParameterValueList;
	soap_default_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues);
	if (!soap_get_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues, "cwmp:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetParameterValues(soap, soap_tmp_cwmp__GetParameterValues.ParameterNames, soap_tmp_cwmp__GetParameterValuesResponse.ParameterList);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Reboot(struct soap *soap)
{	struct cwmp__Reboot soap_tmp_cwmp__Reboot;
	struct cwmp__RebootResponse res;
	soap_default_cwmp__RebootResponse(soap, &res);
	soap_default_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot);
	if (!soap_get_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot, "cwmp:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Reboot(soap, soap_tmp_cwmp__Reboot.Commandkey, &res);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_cwmp__RebootResponse(soap, &res);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__RebootResponse(soap, &res, "cwmp:RebootResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__RebootResponse(soap, &res, "cwmp:RebootResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
