/* soapStub.h
   Generated by gSOAP 2.8.44 for tr069.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_cwmp	"urn:dslforum-org:cwmp-1-0"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20844
# error "GSOAP VERSION 20844 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* cwmp.h:133 */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean {
	xsd__boolean__false_ = 0,
	xsd__boolean__true_ = 1
};
#endif

/* cwmp.h:195 */
#ifndef SOAP_TYPE__cwmp__FaultStruct_FaultCode
#define SOAP_TYPE__cwmp__FaultStruct_FaultCode (18)
/* cwmp:FaultStruct-FaultCode */
enum _cwmp__FaultStruct_FaultCode {
	_cwmp__FaultStruct_FaultCode__0 = 0,
	_cwmp__FaultStruct_FaultCode__9001 = 9001,
	_cwmp__FaultStruct_FaultCode__9002 = 9002,
	_cwmp__FaultStruct_FaultCode__9010 = 9010,
	_cwmp__FaultStruct_FaultCode__9011 = 9011,
	_cwmp__FaultStruct_FaultCode__9012 = 9012
};
#endif

/* cwmp.h:340 */
#ifndef SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification (25)
/* cwmp:SetParameterAttributesStruct-Notification */
enum _cwmp__SetParameterAttributesStruct_Notification {
	_cwmp__SetParameterAttributesStruct_Notification__0 = 0,
	_cwmp__SetParameterAttributesStruct_Notification__1 = 1,
	_cwmp__SetParameterAttributesStruct_Notification__2 = 2
};
#endif

/* cwmp.h:376 */
#ifndef SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification
#define SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification (29)
/* cwmp:ParameterAttributeStruct-Notification */
enum _cwmp__ParameterAttributeStruct_Notification {
	_cwmp__ParameterAttributeStruct_Notification__0 = 0,
	_cwmp__ParameterAttributeStruct_Notification__1 = 1,
	_cwmp__ParameterAttributeStruct_Notification__2 = 2
};
#endif

/* cwmp.h:400 */
#ifndef SOAP_TYPE__cwmp__QueuedTransferStruct_State
#define SOAP_TYPE__cwmp__QueuedTransferStruct_State (31)
/* cwmp:QueuedTransferStruct-State */
enum _cwmp__QueuedTransferStruct_State {
	_cwmp__QueuedTransferStruct_State__1 = 1,
	_cwmp__QueuedTransferStruct_State__2 = 2,
	_cwmp__QueuedTransferStruct_State__3 = 3
};
#endif

/* cwmp.h:434 */
#ifndef SOAP_TYPE__cwmp__OptionStruct_State
#define SOAP_TYPE__cwmp__OptionStruct_State (33)
/* cwmp:OptionStruct-State */
enum _cwmp__OptionStruct_State {
	_cwmp__OptionStruct_State__0 = 0,
	_cwmp__OptionStruct_State__1 = 1,
	_cwmp__OptionStruct_State__2 = 2,
	_cwmp__OptionStruct_State__3 = 3
};
#endif

/* cwmp.h:454 */
#ifndef SOAP_TYPE__cwmp__OptionStruct_Mode
#define SOAP_TYPE__cwmp__OptionStruct_Mode (34)
/* cwmp:OptionStruct-Mode */
enum _cwmp__OptionStruct_Mode {
	_cwmp__OptionStruct_Mode__0 = 0,
	_cwmp__OptionStruct_Mode__1 = 1,
	_cwmp__OptionStruct_Mode__2 = 2
};
#endif

/* cwmp.h:474 */
#ifndef SOAP_TYPE__cwmp__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp__OptionStruct_IsTransferable (37)
/* cwmp:OptionStruct-IsTransferable */
enum _cwmp__OptionStruct_IsTransferable {
	_cwmp__OptionStruct_IsTransferable__0 = 0,
	_cwmp__OptionStruct_IsTransferable__1 = 1
};
#endif

/* cwmp.h:615 */
#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp__SetParameterValuesResponse_Status (50)
/* cwmp:SetParameterValuesResponse-Status */
enum _cwmp__SetParameterValuesResponse_Status {
	_cwmp__SetParameterValuesResponse_Status__0 = 0,
	_cwmp__SetParameterValuesResponse_Status__1 = 1
};
#endif

/* cwmp.h:821 */
#ifndef SOAP_TYPE__cwmp__AddObjectResponse_Status
#define SOAP_TYPE__cwmp__AddObjectResponse_Status (69)
/* cwmp:AddObjectResponse-Status */
enum _cwmp__AddObjectResponse_Status {
	_cwmp__AddObjectResponse_Status__0 = 0,
	_cwmp__AddObjectResponse_Status__1 = 1
};
#endif

/* cwmp.h:871 */
#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp__DeleteObjectResponse_Status (72)
/* cwmp:DeleteObjectResponse-Status */
enum _cwmp__DeleteObjectResponse_Status {
	_cwmp__DeleteObjectResponse_Status__0 = 0,
	_cwmp__DeleteObjectResponse_Status__1 = 1
};
#endif

/* cwmp.h:948 */
#ifndef SOAP_TYPE__cwmp__DownloadResponse_Status
#define SOAP_TYPE__cwmp__DownloadResponse_Status (75)
/* cwmp:DownloadResponse-Status */
enum _cwmp__DownloadResponse_Status {
	_cwmp__DownloadResponse_Status__0 = 0,
	_cwmp__DownloadResponse_Status__1 = 1
};
#endif

/* cwmp.h:1202 */
#ifndef SOAP_TYPE__cwmp__UploadResponse_Status
#define SOAP_TYPE__cwmp__UploadResponse_Status (94)
/* cwmp:UploadResponse-Status */
enum _cwmp__UploadResponse_Status {
	_cwmp__UploadResponse_Status__0 = 0,
	_cwmp__UploadResponse_Status__1 = 1
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct SOAP_ENC__base64;	/* cwmp.h:130 */
struct cwmp__FaultStruct;	/* cwmp.h:190 */
struct cwmp__DeviceIdStruct;	/* cwmp.h:237 */
struct cwmp__EventStruct;	/* cwmp.h:263 */
struct cwmp__ParameterValueStruct;	/* cwmp.h:297 */
struct cwmp__ParameterInfoStruct;	/* cwmp.h:315 */
struct cwmp__SetParameterAttributesStruct;	/* cwmp.h:333 */
struct cwmp__ParameterAttributeStruct;	/* cwmp.h:371 */
struct cwmp__QueuedTransferStruct;	/* cwmp.h:396 */
struct cwmp__OptionStruct;	/* cwmp.h:427 */
struct cwmp__ArgStruct;	/* cwmp.h:497 */
struct _cwmp__Fault_SetParameterValuesFault;	/* cwmp.h:532 */
struct _cwmp__Fault;	/* cwmp.h:517 */
struct _cwmp__GetRPCMethods;	/* cwmp.h:556 */
struct _cwmp__GetRPCMethodsResponse;	/* cwmp.h:573 */
struct _cwmp__SetParameterValues;	/* cwmp.h:592 */
struct _cwmp__SetParameterValuesResponse;	/* cwmp.h:613 */
struct _cwmp__GetParameterValues;	/* cwmp.h:642 */
struct _cwmp__GetParameterValuesResponse;	/* cwmp.h:661 */
struct _cwmp__GetParameterNames;	/* cwmp.h:680 */
struct _cwmp__GetParameterNamesResponse;	/* cwmp.h:702 */
struct _cwmp__SetParameterAttributes;	/* cwmp.h:721 */
struct _cwmp__SetParameterAttributesResponse;	/* cwmp.h:740 */
struct _cwmp__GetParameterAttributes;	/* cwmp.h:757 */
struct _cwmp__GetParameterAttributesResponse;	/* cwmp.h:776 */
struct _cwmp__AddObject;	/* cwmp.h:795 */
struct _cwmp__AddObjectResponse;	/* cwmp.h:816 */
struct _cwmp__DeleteObject;	/* cwmp.h:848 */
struct _cwmp__DeleteObjectResponse;	/* cwmp.h:869 */
struct _cwmp__Download;	/* cwmp.h:898 */
struct _cwmp__DownloadResponse;	/* cwmp.h:946 */
struct _cwmp__Reboot;	/* cwmp.h:979 */
struct _cwmp__RebootResponse;	/* cwmp.h:998 */
struct _cwmp__GetQueuedTransfers;	/* cwmp.h:1015 */
struct _cwmp__GetQueuedTransfersResponse;	/* cwmp.h:1032 */
struct _cwmp__ScheduleInform;	/* cwmp.h:1051 */
struct _cwmp__ScheduleInformResponse;	/* cwmp.h:1072 */
struct _cwmp__SetVouchers;	/* cwmp.h:1089 */
struct _cwmp__SetVouchersResponse;	/* cwmp.h:1108 */
struct _cwmp__GetOptions;	/* cwmp.h:1125 */
struct _cwmp__GetOptionsResponse;	/* cwmp.h:1145 */
struct _cwmp__Upload;	/* cwmp.h:1164 */
struct _cwmp__UploadResponse;	/* cwmp.h:1200 */
struct _cwmp__FactoryReset;	/* cwmp.h:1233 */
struct _cwmp__FactoryResetResponse;	/* cwmp.h:1250 */
struct _cwmp__Inform;	/* cwmp.h:1267 */
struct _cwmp__InformResponse;	/* cwmp.h:1296 */
struct _cwmp__TransferComplete;	/* cwmp.h:1315 */
struct _cwmp__TransferCompleteResponse;	/* cwmp.h:1340 */
struct _cwmp__Kicked;	/* cwmp.h:1357 */
struct _cwmp__KickedResponse;	/* cwmp.h:1386 */
struct _cwmp__RequestDownload;	/* cwmp.h:1406 */
struct _cwmp__RequestDownloadResponse;	/* cwmp.h:1432 */
struct MethodList;	/* cwmp.h:575 */
struct EventList;	/* cwmp.h:1271 */
struct ParameterValueList;	/* cwmp.h:594 */
struct ParameterInfoList;	/* cwmp.h:704 */
struct ParameterNames;	/* cwmp.h:644 */
struct AccessList;	/* cwmp.h:358 */
struct SetParameterAttributesList;	/* cwmp.h:723 */
struct ParameterAttributeList;	/* cwmp.h:778 */
struct TransferList;	/* cwmp.h:1034 */
struct VoucherList;	/* cwmp.h:1091 */
struct OptionList;	/* cwmp.h:1147 */
struct FileTypeArg;	/* cwmp.h:1415 */
struct _cwmp__ID;	/* cwmp.h:1686 */
struct _cwmp__HoldRequests;	/* cwmp.h:1704 */
struct cwmp__InformResponse;	/* tr069.h:22 */
struct cwmp__Inform;	/* tr069.h:33 */

/* cwmp.h:130 */
#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (7)
/* base64Binary XSD type: */
struct SOAP_ENC__base64 {
        unsigned char *__ptr;
        int __size;
};
#endif

/* cwmp.h:190 */
#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (17)
/* complex XSD type 'cwmp:FaultStruct': */
struct cwmp__FaultStruct {
        /** Required element 'FaultCode' of XSD type 'cwmp:FaultStruct-FaultCode' */
        enum _cwmp__FaultStruct_FaultCode FaultCode;
        /** Required element 'FaultString' of XSD type 'xsd:string' */
        char *FaultString;
};
#endif

/* cwmp.h:237 */
#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (19)
/* complex XSD type 'cwmp:DeviceIdStruct': */
struct cwmp__DeviceIdStruct {
        /** Required element 'Manufacturer' of XSD type 'xsd:string' */
        char *Manufacturer;
        /** Required element 'OUI' of XSD type 'xsd:string' */
        char *OUI;
        /** Required element 'ProductClass' of XSD type 'xsd:string' */
        char *ProductClass;
        /** Required element 'SerialNumber' of XSD type 'xsd:string' */
        char *SerialNumber;
};
#endif

/* cwmp.h:263 */
#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (20)
/* complex XSD type 'cwmp:EventStruct': */
struct cwmp__EventStruct {
        /** Required element 'EventCode' of XSD type 'xsd:string' */
        char *EventCode;
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
};
#endif

/* cwmp.h:297 */
#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (21)
/* complex XSD type 'cwmp:ParameterValueStruct': */
struct cwmp__ParameterValueStruct {
        /** Required element 'Name' of XSD type 'xsd:string' */
        char *Name;
        /** Required element 'Value' of XSD type 'xsd:anySimpleType' */
        char *Value;
};
#endif

/* cwmp.h:315 */
#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (22)
/* complex XSD type 'cwmp:ParameterInfoStruct': */
struct cwmp__ParameterInfoStruct {
        /** Required element 'Name' of XSD type 'xsd:string' */
        char *Name;
        /** Required element 'Writable' of XSD type 'xsd:boolean' */
        enum xsd__boolean Writable;
};
#endif

/* cwmp.h:333 */
#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (23)
/* complex XSD type 'cwmp:SetParameterAttributesStruct': */
struct cwmp__SetParameterAttributesStruct {
        /** Required nillable (xsi:nil when NULL) element 'Name' of XSD type 'xsd:string' */
        char **Name;
        /** Required element 'NotificationChange' of XSD type 'xsd:boolean' */
        enum xsd__boolean NotificationChange;
        /** Required element 'Notification' of XSD type 'cwmp:SetParameterAttributesStruct-Notification' */
        enum _cwmp__SetParameterAttributesStruct_Notification Notification;
        /** Required element 'AccessListChange' of XSD type 'xsd:boolean' */
        enum xsd__boolean AccessListChange;
        /** Required element 'AccessList' of XSD type 'ArrayOfstring' */
        struct AccessList *AccessList;
};
#endif

/* cwmp.h:371 */
#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (28)
/* complex XSD type 'cwmp:ParameterAttributeStruct': */
struct cwmp__ParameterAttributeStruct {
        /** Required element 'Name' of XSD type 'xsd:string' */
        char *Name;
        /** Required element 'Notification' of XSD type 'cwmp:ParameterAttributeStruct-Notification' */
        enum _cwmp__ParameterAttributeStruct_Notification Notification;
        /** Required element 'AccessList' of XSD type 'ArrayOfstring' */
        struct AccessList *AccessList;
};
#endif

/* cwmp.h:396 */
#ifndef SOAP_TYPE_cwmp__QueuedTransferStruct
#define SOAP_TYPE_cwmp__QueuedTransferStruct (30)
/* complex XSD type 'cwmp:QueuedTransferStruct': */
struct cwmp__QueuedTransferStruct {
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
        /** Required element 'State' of XSD type 'cwmp:QueuedTransferStruct-State' */
        enum _cwmp__QueuedTransferStruct_State State;
};
#endif

/* cwmp.h:427 */
#ifndef SOAP_TYPE_cwmp__OptionStruct
#define SOAP_TYPE_cwmp__OptionStruct (32)
/* complex XSD type 'cwmp:OptionStruct': */
struct cwmp__OptionStruct {
        /** Required element 'OptionName' of XSD type 'xsd:string' */
        char *OptionName;
        /** Required element 'VoucherSN' of XSD type 'xsd:unsignedInt' */
        unsigned int VoucherSN;
        /** Required element 'State' of XSD type 'cwmp:OptionStruct-State' */
        enum _cwmp__OptionStruct_State State;
        /** Required element 'Mode' of XSD type 'cwmp:OptionStruct-Mode' */
        enum _cwmp__OptionStruct_Mode Mode;
        /** Required element 'StartDate' of XSD type 'xsd:dateTime' */
        time_t StartDate;
        /** Optional element 'ExpirationDate' of XSD type 'xsd:dateTime' */
        time_t *ExpirationDate;
        /** Required element 'IsTransferable' of XSD type 'cwmp:OptionStruct-IsTransferable' */
        enum _cwmp__OptionStruct_IsTransferable IsTransferable;
};
#endif

/* cwmp.h:497 */
#ifndef SOAP_TYPE_cwmp__ArgStruct
#define SOAP_TYPE_cwmp__ArgStruct (38)
/* complex XSD type 'cwmp:ArgStruct': */
struct cwmp__ArgStruct {
        /** Required element 'Name' of XSD type 'xsd:string' */
        char *Name;
        /** Required element 'Value' of XSD type 'xsd:string' */
        char *Value;
};
#endif

/* cwmp.h:532 */
#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (40)
/* complex XSD type 'cwmp:Fault-SetParameterValuesFault': */
struct _cwmp__Fault_SetParameterValuesFault {
        /** Required element 'ParameterName' of XSD type 'xsd:string' */
        char *ParameterName;
        /** Required element 'FaultCode' of XSD type 'cwmp:FaultCodeType' */
        char *FaultCode;
        /** Optional element 'FaultString' of XSD type 'xsd:string' */
        char *FaultString;
};
#endif

/* cwmp.h:517 */
#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (39)
/* complex XSD type 'cwmp:Fault': */
struct _cwmp__Fault {
        /** Required element 'FaultCode' of XSD type 'cwmp:FaultCodeType' */
        char *FaultCode;
        /** Optional element 'FaultString' of XSD type 'xsd:string' */
        char *FaultString;
        /** Sequence of elements 'SetParameterValuesFault' of XSD type 'cwmp:Fault-SetParameterValuesFault' stored in dynamic array SetParameterValuesFault of length __sizeSetParameterValuesFault */
        int __sizeSetParameterValuesFault;
        struct _cwmp__Fault_SetParameterValuesFault *SetParameterValuesFault;
};
#endif

/* cwmp.h:556 */
#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (42)
/* complex XSD type 'cwmp:GetRPCMethods': */
struct _cwmp__GetRPCMethods {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:573 */
#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (43)
/* complex XSD type 'cwmp:GetRPCMethodsResponse': */
struct _cwmp__GetRPCMethodsResponse {
        /** Required element 'MethodList' of XSD type 'ArrayOfstring' */
        struct MethodList *MethodList;
};
#endif

/* cwmp.h:592 */
#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (46)
/* complex XSD type 'cwmp:SetParameterValues': */
struct _cwmp__SetParameterValues {
        /** Required element 'ParameterList' of XSD type 'ArrayOfParameterValueStruct' */
        struct ParameterValueList *ParameterList;
        /** Required element 'ParameterKey' of XSD type 'cwmp:ParameterKeyType' */
        char *ParameterKey;
};
#endif

/* cwmp.h:613 */
#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (49)
/* complex XSD type 'cwmp:SetParameterValuesResponse': */
struct _cwmp__SetParameterValuesResponse {
        /** Required element 'Status' of XSD type 'cwmp:SetParameterValuesResponse-Status' */
        enum _cwmp__SetParameterValuesResponse_Status Status;
};
#endif

/* cwmp.h:642 */
#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (51)
/* complex XSD type 'cwmp:GetParameterValues': */
struct _cwmp__GetParameterValues {
        /** Required element 'ParameterNames' of XSD type 'ArrayOfstring' */
        struct ParameterNames *ParameterNames;
};
#endif

/* cwmp.h:661 */
#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (54)
/* complex XSD type 'cwmp:GetParameterValuesResponse': */
struct _cwmp__GetParameterValuesResponse {
        /** Required element 'ParameterList' of XSD type 'ArrayOfParameterValueStruct' */
        struct ParameterValueList *ParameterList;
};
#endif

/* cwmp.h:680 */
#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (55)
/* complex XSD type 'cwmp:GetParameterNames': */
struct _cwmp__GetParameterNames {
        /** Required nillable (xsi:nil when NULL) element 'ParameterPath' of XSD type 'xsd:string' */
        char **ParameterPath;
        /** Required element 'NextLevel' of XSD type 'xsd:boolean' */
        enum xsd__boolean NextLevel;
};
#endif

/* cwmp.h:702 */
#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (56)
/* complex XSD type 'cwmp:GetParameterNamesResponse': */
struct _cwmp__GetParameterNamesResponse {
        /** Required element 'ParameterList' of XSD type 'ArrayOfParameterInfoStruct' */
        struct ParameterInfoList *ParameterList;
};
#endif

/* cwmp.h:721 */
#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (59)
/* complex XSD type 'cwmp:SetParameterAttributes': */
struct _cwmp__SetParameterAttributes {
        /** Required element 'ParameterList' of XSD type 'ArrayOfSetParameterAttributesStruct' */
        struct SetParameterAttributesList *ParameterList;
};
#endif

/* cwmp.h:740 */
#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (62)
/* complex XSD type 'cwmp:SetParameterAttributesResponse': */
struct _cwmp__SetParameterAttributesResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:757 */
#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (63)
/* complex XSD type 'cwmp:GetParameterAttributes': */
struct _cwmp__GetParameterAttributes {
        /** Required element 'ParameterNames' of XSD type 'ArrayOfstring' */
        struct ParameterNames *ParameterNames;
};
#endif

/* cwmp.h:776 */
#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (64)
/* complex XSD type 'cwmp:GetParameterAttributesResponse': */
struct _cwmp__GetParameterAttributesResponse {
        /** Required element 'ParameterList' of XSD type 'ArrayOfParameterAttributeStruct' */
        struct ParameterAttributeList *ParameterList;
};
#endif

/* cwmp.h:795 */
#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (67)
/* complex XSD type 'cwmp:AddObject': */
struct _cwmp__AddObject {
        /** Required element 'ObjectName' of XSD type 'cwmp:ObjectNameType' */
        char *ObjectName;
        /** Required element 'ParameterKey' of XSD type 'cwmp:ParameterKeyType' */
        char *ParameterKey;
};
#endif

/* cwmp.h:816 */
#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (68)
/* complex XSD type 'cwmp:AddObjectResponse': */
struct _cwmp__AddObjectResponse {
        /** Required element 'InstanceNumber' of XSD type 'xsd:unsignedInt' */
        unsigned int InstanceNumber;
        /** Required element 'Status' of XSD type 'cwmp:AddObjectResponse-Status' */
        enum _cwmp__AddObjectResponse_Status Status;
};
#endif

/* cwmp.h:848 */
#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (70)
/* complex XSD type 'cwmp:DeleteObject': */
struct _cwmp__DeleteObject {
        /** Required element 'ObjectName' of XSD type 'cwmp:ObjectNameType' */
        char *ObjectName;
        /** Required element 'ParameterKey' of XSD type 'cwmp:ParameterKeyType' */
        char *ParameterKey;
};
#endif

/* cwmp.h:869 */
#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (71)
/* complex XSD type 'cwmp:DeleteObjectResponse': */
struct _cwmp__DeleteObjectResponse {
        /** Required element 'Status' of XSD type 'cwmp:DeleteObjectResponse-Status' */
        enum _cwmp__DeleteObjectResponse_Status Status;
};
#endif

/* cwmp.h:898 */
#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (73)
/* complex XSD type 'cwmp:Download': */
struct _cwmp__Download {
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
        /** Required element 'FileType' of XSD type 'xsd:string' */
        char *FileType;
        /** Required element 'URL' of XSD type 'xsd:string' */
        char *URL;
        /** Required element 'Username' of XSD type 'xsd:string' */
        char *Username;
        /** Required element 'Password' of XSD type 'xsd:string' */
        char *Password;
        /** Required element 'FileSize' of XSD type 'xsd:unsignedInt' */
        unsigned int FileSize;
        /** Required element 'TargetFileName' of XSD type 'xsd:string' */
        char *TargetFileName;
        /** Required element 'DelaySeconds' of XSD type 'xsd:unsignedInt' */
        unsigned int DelaySeconds;
        /** Required element 'SuccessURL' of XSD type 'xsd:string' */
        char *SuccessURL;
        /** Required element 'FailureURL' of XSD type 'xsd:string' */
        char *FailureURL;
};
#endif

/* cwmp.h:946 */
#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (74)
/* complex XSD type 'cwmp:DownloadResponse': */
struct _cwmp__DownloadResponse {
        /** Required element 'Status' of XSD type 'cwmp:DownloadResponse-Status' */
        enum _cwmp__DownloadResponse_Status Status;
        /** Required element 'StartTime' of XSD type 'xsd:dateTime' */
        time_t StartTime;
        /** Required element 'CompleteTime' of XSD type 'xsd:dateTime' */
        time_t CompleteTime;
};
#endif

/* cwmp.h:979 */
#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (76)
/* complex XSD type 'cwmp:Reboot': */
struct _cwmp__Reboot {
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
};
#endif

/* cwmp.h:998 */
#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (77)
/* complex XSD type 'cwmp:RebootResponse': */
struct _cwmp__RebootResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1015 */
#ifndef SOAP_TYPE__cwmp__GetQueuedTransfers
#define SOAP_TYPE__cwmp__GetQueuedTransfers (78)
/* complex XSD type 'cwmp:GetQueuedTransfers': */
struct _cwmp__GetQueuedTransfers {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1032 */
#ifndef SOAP_TYPE__cwmp__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetQueuedTransfersResponse (79)
/* complex XSD type 'cwmp:GetQueuedTransfersResponse': */
struct _cwmp__GetQueuedTransfersResponse {
        /** Required element 'TransferList' of XSD type 'ArrayOfQueuedTransferStruct' */
        struct TransferList *TransferList;
};
#endif

/* cwmp.h:1051 */
#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (82)
/* complex XSD type 'cwmp:ScheduleInform': */
struct _cwmp__ScheduleInform {
        /** Required element 'DelaySeconds' of XSD type 'xsd:unsignedInt' */
        unsigned int DelaySeconds;
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
};
#endif

/* cwmp.h:1072 */
#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (83)
/* complex XSD type 'cwmp:ScheduleInformResponse': */
struct _cwmp__ScheduleInformResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1089 */
#ifndef SOAP_TYPE__cwmp__SetVouchers
#define SOAP_TYPE__cwmp__SetVouchers (84)
/* complex XSD type 'cwmp:SetVouchers': */
struct _cwmp__SetVouchers {
        /** Required element 'VoucherList' of XSD type 'ArrayOfbase64' */
        struct VoucherList *VoucherList;
};
#endif

/* cwmp.h:1108 */
#ifndef SOAP_TYPE__cwmp__SetVouchersResponse
#define SOAP_TYPE__cwmp__SetVouchersResponse (87)
/* complex XSD type 'cwmp:SetVouchersResponse': */
struct _cwmp__SetVouchersResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1125 */
#ifndef SOAP_TYPE__cwmp__GetOptions
#define SOAP_TYPE__cwmp__GetOptions (88)
/* complex XSD type 'cwmp:GetOptions': */
struct _cwmp__GetOptions {
        /** Required element 'OptionName' of XSD type 'xsd:string' */
        char *OptionName;
};
#endif

/* cwmp.h:1145 */
#ifndef SOAP_TYPE__cwmp__GetOptionsResponse
#define SOAP_TYPE__cwmp__GetOptionsResponse (89)
/* complex XSD type 'cwmp:GetOptionsResponse': */
struct _cwmp__GetOptionsResponse {
        /** Required element 'OptionList' of XSD type 'ArrayOfOptionStruct' */
        struct OptionList *OptionList;
};
#endif

/* cwmp.h:1164 */
#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (92)
/* complex XSD type 'cwmp:Upload': */
struct _cwmp__Upload {
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
        /** Required element 'FileType' of XSD type 'xsd:string' */
        char *FileType;
        /** Required element 'URL' of XSD type 'xsd:string' */
        char *URL;
        /** Required element 'Username' of XSD type 'xsd:string' */
        char *Username;
        /** Required element 'Password' of XSD type 'xsd:string' */
        char *Password;
        /** Required element 'DelaySeconds' of XSD type 'xsd:unsignedInt' */
        unsigned int DelaySeconds;
};
#endif

/* cwmp.h:1200 */
#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (93)
/* complex XSD type 'cwmp:UploadResponse': */
struct _cwmp__UploadResponse {
        /** Required element 'Status' of XSD type 'cwmp:UploadResponse-Status' */
        enum _cwmp__UploadResponse_Status Status;
        /** Required element 'StartTime' of XSD type 'xsd:dateTime' */
        time_t StartTime;
        /** Required element 'CompleteTime' of XSD type 'xsd:dateTime' */
        time_t CompleteTime;
};
#endif

/* cwmp.h:1233 */
#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (95)
/* complex XSD type 'cwmp:FactoryReset': */
struct _cwmp__FactoryReset {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1250 */
#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (96)
/* complex XSD type 'cwmp:FactoryResetResponse': */
struct _cwmp__FactoryResetResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1267 */
#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (97)
/* complex XSD type 'cwmp:Inform': */
struct _cwmp__Inform {
        /** Required element 'DeviceId' of XSD type 'cwmp:DeviceIdStruct' */
        struct cwmp__DeviceIdStruct *DeviceId;
        /** Required element 'Event' of XSD type 'ArrayOfEventStruct' */
        struct EventList *Event;
        /** Required element 'MaxEnvelopes' of XSD type 'xsd:unsignedInt' */
        unsigned int MaxEnvelopes;
        /** Required element 'CurrentTime' of XSD type 'xsd:dateTime' */
        time_t CurrentTime;
        /** Required element 'RetryCount' of XSD type 'xsd:unsignedInt' */
        unsigned int RetryCount;
        /** Required element 'ParameterList' of XSD type 'ArrayOfParameterValueStruct' */
        struct ParameterValueList *ParameterList;
};
#endif

/* cwmp.h:1296 */
#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (101)
/* complex XSD type 'cwmp:InformResponse': */
struct _cwmp__InformResponse {
        /** Required element 'MaxEnvelopes' of XSD type 'xsd:unsignedInt' */
        unsigned int MaxEnvelopes;
};
#endif

/* cwmp.h:1315 */
#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (102)
/* complex XSD type 'cwmp:TransferComplete': */
struct _cwmp__TransferComplete {
        /** Required element 'CommandKey' of XSD type 'cwmp:CommandKeyType' */
        char *CommandKey;
        /** Required element 'FaultStruct' of XSD type 'cwmp:FaultStruct' */
        struct cwmp__FaultStruct *FaultStruct;
        /** Required element 'StartTime' of XSD type 'xsd:dateTime' */
        time_t StartTime;
        /** Required element 'CompleteTime' of XSD type 'xsd:dateTime' */
        time_t CompleteTime;
};
#endif

/* cwmp.h:1340 */
#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (104)
/* complex XSD type 'cwmp:TransferCompleteResponse': */
struct _cwmp__TransferCompleteResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:1357 */
#ifndef SOAP_TYPE__cwmp__Kicked
#define SOAP_TYPE__cwmp__Kicked (105)
/* complex XSD type 'cwmp:Kicked': */
struct _cwmp__Kicked {
        /** Required element 'Command' of XSD type 'xsd:string' */
        char *Command;
        /** Required element 'Referer' of XSD type 'xsd:string' */
        char *Referer;
        /** Required element 'Arg' of XSD type 'xsd:string' */
        char *Arg;
        /** Required element 'Next' of XSD type 'xsd:string' */
        char *Next;
};
#endif

/* cwmp.h:1386 */
#ifndef SOAP_TYPE__cwmp__KickedResponse
#define SOAP_TYPE__cwmp__KickedResponse (106)
/* complex XSD type 'cwmp:KickedResponse': */
struct _cwmp__KickedResponse {
        /** Required element 'NextURL' of XSD type 'xsd:string' */
        char *NextURL;
};
#endif

/* cwmp.h:1406 */
#ifndef SOAP_TYPE__cwmp__RequestDownload
#define SOAP_TYPE__cwmp__RequestDownload (107)
/* complex XSD type 'cwmp:RequestDownload': */
struct _cwmp__RequestDownload {
        /** Required element 'FileType' of XSD type 'xsd:string' */
        char *FileType;
        /** Required element 'FileTypeArg' of XSD type 'ArrayOfArgStruct' */
        struct FileTypeArg *FileTypeArg;
};
#endif

/* cwmp.h:1432 */
#ifndef SOAP_TYPE__cwmp__RequestDownloadResponse
#define SOAP_TYPE__cwmp__RequestDownloadResponse (110)
/* complex XSD type 'cwmp:RequestDownloadResponse': */
struct _cwmp__RequestDownloadResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* cwmp.h:575 */
#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (44)
/* SOAP encoded array of xsd:string schema type: */
struct MethodList {
        char **__ptrstring;
        int __size;
};
#endif

/* cwmp.h:1271 */
#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (99)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct EventList {
        struct cwmp__EventStruct **__ptrEventStruct;
        int __size;
};
#endif

/* cwmp.h:594 */
#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (47)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct ParameterValueList {
        struct cwmp__ParameterValueStruct **__ptrParameterValueStruct;
        int __size;
};
#endif

/* cwmp.h:704 */
#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (57)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
struct ParameterInfoList {
        struct cwmp__ParameterInfoStruct **__ptrParameterInfoStruct;
        int __size;
};
#endif

/* cwmp.h:644 */
#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (52)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames {
        char **__ptrstring;
        int __size;
};
#endif

/* cwmp.h:358 */
#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (26)
/* SOAP encoded array of xsd:string schema type: */
struct AccessList {
        char **__ptrstring;
        int __size;
};
#endif

/* cwmp.h:723 */
#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (60)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList {
        struct cwmp__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
        int __size;
};
#endif

/* cwmp.h:778 */
#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (65)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct ParameterAttributeList {
        struct cwmp__ParameterAttributeStruct **__ptrParameterAttributeStruct;
        int __size;
};
#endif

/* cwmp.h:1034 */
#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (80)
/* SOAP encoded array of cwmp:QueuedTransferStruct schema type: */
struct TransferList {
        struct cwmp__QueuedTransferStruct **__ptrQueuedTransferStruct;
        int __size;
};
#endif

/* cwmp.h:1091 */
#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (85)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct VoucherList {
        struct SOAP_ENC__base64 *__ptrbase64;
        int __size;
};
#endif

/* cwmp.h:1147 */
#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (90)
/* SOAP encoded array of cwmp:OptionStruct schema type: */
struct OptionList {
        struct cwmp__OptionStruct **__ptrOptionStruct;
        int __size;
};
#endif

/* cwmp.h:1415 */
#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (108)
/* SOAP encoded array of cwmp:ArgStruct schema type: */
struct FileTypeArg {
        struct cwmp__ArgStruct **__ptrArgStruct;
        int __size;
};
#endif

/* cwmp.h:1686 */
#ifndef SOAP_TYPE__cwmp__ID
#define SOAP_TYPE__cwmp__ID (128)
/* simple XSD type 'cwmp:ID': */
struct _cwmp__ID {
        /** Simple content of XSD type 'xsd:string' wrapped by this struct */
        char *__item;
        /** Required attribute 'SOAP-ENV:mustUnderstand' of XSD type 'xsd:string' */
        char *SOAP_ENV__mustUnderstand;
};
#endif

/* cwmp.h:1704 */
#ifndef SOAP_TYPE__cwmp__HoldRequests
#define SOAP_TYPE__cwmp__HoldRequests (129)
/* simple XSD type 'cwmp:HoldRequests': */
struct _cwmp__HoldRequests {
        /** Simple content of XSD type 'xsd:boolean' wrapped by this struct */
        enum xsd__boolean __item;
        /** Required attribute 'SOAP-ENV:mustUnderstand' of XSD type 'xsd:string' */
        char *SOAP_ENV__mustUnderstand;
};
#endif

/* tr069.h:16 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (130)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
        /** MustUnderstand */
        char *cwmp__ID;
        /** MustUnderstand */
        enum xsd__boolean cwmp__HoldRequests;
};
#endif
#endif

/* tr069.h:22 */
#ifndef SOAP_TYPE_cwmp__InformResponse
#define SOAP_TYPE_cwmp__InformResponse (131)
/* complex XSD type 'cwmp:InformResponse': */
struct cwmp__InformResponse {
        /** Required element 'MaxEnvelopes' of XSD type 'xsd:unsignedInt' */
        unsigned int MaxEnvelopes;
};
#endif

/* tr069.h:33 */
#ifndef SOAP_TYPE_cwmp__Inform
#define SOAP_TYPE_cwmp__Inform (134)
/* complex XSD type 'cwmp:Inform': */
struct cwmp__Inform {
        /** Optional element 'DeviceId' of XSD type 'cwmp:DeviceIdStruct' */
        struct cwmp__DeviceIdStruct *DeviceId;
        /** Optional element 'Event' of XSD type 'ArrayOfEventStruct' */
        struct EventList *Event;
        /** Required element 'MaxEnvelopes' of XSD type 'xsd:unsignedInt' */
        unsigned int MaxEnvelopes;
        /** Required element 'CurrentTime' of XSD type 'xsd:dateTime' */
        time_t CurrentTime;
        /** Required element 'RetryCount' of XSD type 'xsd:unsignedInt' */
        unsigned int RetryCount;
        /** Optional element 'ParameterList' of XSD type 'ArrayOfParameterValueStruct' */
        struct ParameterValueList *ParameterList;
};
#endif

/* tr069.h:35 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (135)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* tr069.h:35 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (137)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* tr069.h:35 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (140)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* tr069.h:35 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (141)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* cwmp.h:120 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* cwmp.h:120 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/* cwmp.h:136 */
#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (12)
typedef char *xsd__anySimpleType;
#endif

/* cwmp.h:151 */
#ifndef SOAP_TYPE_cwmp__FaultCodeType
#define SOAP_TYPE_cwmp__FaultCodeType (13)
typedef char *cwmp__FaultCodeType;
#endif

/* cwmp.h:156 */
#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (14)
typedef char *cwmp__ParameterKeyType;
#endif

/* cwmp.h:161 */
#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (15)
typedef char *cwmp__CommandKeyType;
#endif

/* cwmp.h:167 */
#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (16)
typedef char *cwmp__ObjectNameType;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* unsigned char has binding name 'unsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif

/* unsigned int has binding name 'unsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif

/* time_t has binding name 'dateTime' for type 'xsd:dateTime' */
#ifndef SOAP_TYPE_dateTime
#define SOAP_TYPE_dateTime (35)
#endif

/* enum _cwmp__UploadResponse_Status has binding name '_cwmp__UploadResponse_Status' for type 'cwmp:UploadResponse-Status' */
#ifndef SOAP_TYPE__cwmp__UploadResponse_Status
#define SOAP_TYPE__cwmp__UploadResponse_Status (94)
#endif

/* enum _cwmp__DownloadResponse_Status has binding name '_cwmp__DownloadResponse_Status' for type 'cwmp:DownloadResponse-Status' */
#ifndef SOAP_TYPE__cwmp__DownloadResponse_Status
#define SOAP_TYPE__cwmp__DownloadResponse_Status (75)
#endif

/* enum _cwmp__DeleteObjectResponse_Status has binding name '_cwmp__DeleteObjectResponse_Status' for type 'cwmp:DeleteObjectResponse-Status' */
#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp__DeleteObjectResponse_Status (72)
#endif

/* enum _cwmp__AddObjectResponse_Status has binding name '_cwmp__AddObjectResponse_Status' for type 'cwmp:AddObjectResponse-Status' */
#ifndef SOAP_TYPE__cwmp__AddObjectResponse_Status
#define SOAP_TYPE__cwmp__AddObjectResponse_Status (69)
#endif

/* enum _cwmp__SetParameterValuesResponse_Status has binding name '_cwmp__SetParameterValuesResponse_Status' for type 'cwmp:SetParameterValuesResponse-Status' */
#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp__SetParameterValuesResponse_Status (50)
#endif

/* enum _cwmp__OptionStruct_IsTransferable has binding name '_cwmp__OptionStruct_IsTransferable' for type 'cwmp:OptionStruct-IsTransferable' */
#ifndef SOAP_TYPE__cwmp__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp__OptionStruct_IsTransferable (37)
#endif

/* enum _cwmp__OptionStruct_Mode has binding name '_cwmp__OptionStruct_Mode' for type 'cwmp:OptionStruct-Mode' */
#ifndef SOAP_TYPE__cwmp__OptionStruct_Mode
#define SOAP_TYPE__cwmp__OptionStruct_Mode (34)
#endif

/* enum _cwmp__OptionStruct_State has binding name '_cwmp__OptionStruct_State' for type 'cwmp:OptionStruct-State' */
#ifndef SOAP_TYPE__cwmp__OptionStruct_State
#define SOAP_TYPE__cwmp__OptionStruct_State (33)
#endif

/* enum _cwmp__QueuedTransferStruct_State has binding name '_cwmp__QueuedTransferStruct_State' for type 'cwmp:QueuedTransferStruct-State' */
#ifndef SOAP_TYPE__cwmp__QueuedTransferStruct_State
#define SOAP_TYPE__cwmp__QueuedTransferStruct_State (31)
#endif

/* enum _cwmp__ParameterAttributeStruct_Notification has binding name '_cwmp__ParameterAttributeStruct_Notification' for type 'cwmp:ParameterAttributeStruct-Notification' */
#ifndef SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification
#define SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification (29)
#endif

/* enum _cwmp__SetParameterAttributesStruct_Notification has binding name '_cwmp__SetParameterAttributesStruct_Notification' for type 'cwmp:SetParameterAttributesStruct-Notification' */
#ifndef SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification (25)
#endif

/* enum _cwmp__FaultStruct_FaultCode has binding name '_cwmp__FaultStruct_FaultCode' for type 'cwmp:FaultStruct-FaultCode' */
#ifndef SOAP_TYPE__cwmp__FaultStruct_FaultCode
#define SOAP_TYPE__cwmp__FaultStruct_FaultCode (18)
#endif

/* enum xsd__boolean has binding name 'xsd__boolean' for type 'xsd:boolean' */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (141)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (140)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (137)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (135)
#endif

/* struct cwmp__Inform has binding name 'cwmp__Inform' for type 'cwmp:Inform' */
#ifndef SOAP_TYPE_cwmp__Inform
#define SOAP_TYPE_cwmp__Inform (134)
#endif

/* struct cwmp__InformResponse has binding name 'cwmp__InformResponse' for type 'cwmp:InformResponse' */
#ifndef SOAP_TYPE_cwmp__InformResponse
#define SOAP_TYPE_cwmp__InformResponse (131)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (130)
#endif

/* struct _cwmp__HoldRequests has binding name '_cwmp__HoldRequests' for type '' */
#ifndef SOAP_TYPE__cwmp__HoldRequests
#define SOAP_TYPE__cwmp__HoldRequests (129)
#endif

/* struct _cwmp__ID has binding name '_cwmp__ID' for type '' */
#ifndef SOAP_TYPE__cwmp__ID
#define SOAP_TYPE__cwmp__ID (128)
#endif

/* struct _cwmp__RequestDownloadResponse has binding name '_cwmp__RequestDownloadResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__RequestDownloadResponse
#define SOAP_TYPE__cwmp__RequestDownloadResponse (110)
#endif

/* struct FileTypeArg has binding name 'FileTypeArg' for type 'cwmp:ArgStruct' */
#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (108)
#endif

/* struct _cwmp__RequestDownload has binding name '_cwmp__RequestDownload' for type '' */
#ifndef SOAP_TYPE__cwmp__RequestDownload
#define SOAP_TYPE__cwmp__RequestDownload (107)
#endif

/* struct _cwmp__KickedResponse has binding name '_cwmp__KickedResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__KickedResponse
#define SOAP_TYPE__cwmp__KickedResponse (106)
#endif

/* struct _cwmp__Kicked has binding name '_cwmp__Kicked' for type '' */
#ifndef SOAP_TYPE__cwmp__Kicked
#define SOAP_TYPE__cwmp__Kicked (105)
#endif

/* struct _cwmp__TransferCompleteResponse has binding name '_cwmp__TransferCompleteResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (104)
#endif

/* struct _cwmp__TransferComplete has binding name '_cwmp__TransferComplete' for type '' */
#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (102)
#endif

/* struct _cwmp__InformResponse has binding name '_cwmp__InformResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (101)
#endif

/* struct EventList has binding name 'EventList' for type 'cwmp:EventStruct' */
#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (99)
#endif

/* struct _cwmp__Inform has binding name '_cwmp__Inform' for type '' */
#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (97)
#endif

/* struct _cwmp__FactoryResetResponse has binding name '_cwmp__FactoryResetResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (96)
#endif

/* struct _cwmp__FactoryReset has binding name '_cwmp__FactoryReset' for type '' */
#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (95)
#endif

/* struct _cwmp__UploadResponse has binding name '_cwmp__UploadResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (93)
#endif

/* struct _cwmp__Upload has binding name '_cwmp__Upload' for type '' */
#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (92)
#endif

/* struct OptionList has binding name 'OptionList' for type 'cwmp:OptionStruct' */
#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (90)
#endif

/* struct _cwmp__GetOptionsResponse has binding name '_cwmp__GetOptionsResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__GetOptionsResponse
#define SOAP_TYPE__cwmp__GetOptionsResponse (89)
#endif

/* struct _cwmp__GetOptions has binding name '_cwmp__GetOptions' for type '' */
#ifndef SOAP_TYPE__cwmp__GetOptions
#define SOAP_TYPE__cwmp__GetOptions (88)
#endif

/* struct _cwmp__SetVouchersResponse has binding name '_cwmp__SetVouchersResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__SetVouchersResponse
#define SOAP_TYPE__cwmp__SetVouchersResponse (87)
#endif

/* struct VoucherList has binding name 'VoucherList' for type 'SOAP-ENC:base64' */
#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (85)
#endif

/* struct _cwmp__SetVouchers has binding name '_cwmp__SetVouchers' for type '' */
#ifndef SOAP_TYPE__cwmp__SetVouchers
#define SOAP_TYPE__cwmp__SetVouchers (84)
#endif

/* struct _cwmp__ScheduleInformResponse has binding name '_cwmp__ScheduleInformResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (83)
#endif

/* struct _cwmp__ScheduleInform has binding name '_cwmp__ScheduleInform' for type '' */
#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (82)
#endif

/* struct TransferList has binding name 'TransferList' for type 'cwmp:QueuedTransferStruct' */
#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (80)
#endif

/* struct _cwmp__GetQueuedTransfersResponse has binding name '_cwmp__GetQueuedTransfersResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetQueuedTransfersResponse (79)
#endif

/* struct _cwmp__GetQueuedTransfers has binding name '_cwmp__GetQueuedTransfers' for type '' */
#ifndef SOAP_TYPE__cwmp__GetQueuedTransfers
#define SOAP_TYPE__cwmp__GetQueuedTransfers (78)
#endif

/* struct _cwmp__RebootResponse has binding name '_cwmp__RebootResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (77)
#endif

/* struct _cwmp__Reboot has binding name '_cwmp__Reboot' for type '' */
#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (76)
#endif

/* struct _cwmp__DownloadResponse has binding name '_cwmp__DownloadResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (74)
#endif

/* struct _cwmp__Download has binding name '_cwmp__Download' for type '' */
#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (73)
#endif

/* struct _cwmp__DeleteObjectResponse has binding name '_cwmp__DeleteObjectResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (71)
#endif

/* struct _cwmp__DeleteObject has binding name '_cwmp__DeleteObject' for type '' */
#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (70)
#endif

/* struct _cwmp__AddObjectResponse has binding name '_cwmp__AddObjectResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (68)
#endif

/* struct _cwmp__AddObject has binding name '_cwmp__AddObject' for type '' */
#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (67)
#endif

/* struct ParameterAttributeList has binding name 'ParameterAttributeList' for type 'cwmp:ParameterAttributeStruct' */
#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (65)
#endif

/* struct _cwmp__GetParameterAttributesResponse has binding name '_cwmp__GetParameterAttributesResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (64)
#endif

/* struct _cwmp__GetParameterAttributes has binding name '_cwmp__GetParameterAttributes' for type '' */
#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (63)
#endif

/* struct _cwmp__SetParameterAttributesResponse has binding name '_cwmp__SetParameterAttributesResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (62)
#endif

/* struct SetParameterAttributesList has binding name 'SetParameterAttributesList' for type 'cwmp:SetParameterAttributesStruct' */
#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (60)
#endif

/* struct _cwmp__SetParameterAttributes has binding name '_cwmp__SetParameterAttributes' for type '' */
#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (59)
#endif

/* struct ParameterInfoList has binding name 'ParameterInfoList' for type 'cwmp:ParameterInfoStruct' */
#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (57)
#endif

/* struct _cwmp__GetParameterNamesResponse has binding name '_cwmp__GetParameterNamesResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (56)
#endif

/* struct _cwmp__GetParameterNames has binding name '_cwmp__GetParameterNames' for type '' */
#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (55)
#endif

/* struct _cwmp__GetParameterValuesResponse has binding name '_cwmp__GetParameterValuesResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (54)
#endif

/* struct ParameterNames has binding name 'ParameterNames' for type 'xsd:string' */
#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (52)
#endif

/* struct _cwmp__GetParameterValues has binding name '_cwmp__GetParameterValues' for type '' */
#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (51)
#endif

/* struct _cwmp__SetParameterValuesResponse has binding name '_cwmp__SetParameterValuesResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (49)
#endif

/* struct ParameterValueList has binding name 'ParameterValueList' for type 'cwmp:ParameterValueStruct' */
#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (47)
#endif

/* struct _cwmp__SetParameterValues has binding name '_cwmp__SetParameterValues' for type '' */
#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (46)
#endif

/* struct MethodList has binding name 'MethodList' for type 'xsd:string' */
#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (44)
#endif

/* struct _cwmp__GetRPCMethodsResponse has binding name '_cwmp__GetRPCMethodsResponse' for type '' */
#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (43)
#endif

/* struct _cwmp__GetRPCMethods has binding name '_cwmp__GetRPCMethods' for type '' */
#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (42)
#endif

/* struct _cwmp__Fault_SetParameterValuesFault has binding name '_cwmp__Fault_SetParameterValuesFault' for type '' */
#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (40)
#endif

/* struct _cwmp__Fault has binding name '_cwmp__Fault' for type '' */
#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (39)
#endif

/* struct cwmp__ArgStruct has binding name 'cwmp__ArgStruct' for type 'cwmp:ArgStruct' */
#ifndef SOAP_TYPE_cwmp__ArgStruct
#define SOAP_TYPE_cwmp__ArgStruct (38)
#endif

/* struct cwmp__OptionStruct has binding name 'cwmp__OptionStruct' for type 'cwmp:OptionStruct' */
#ifndef SOAP_TYPE_cwmp__OptionStruct
#define SOAP_TYPE_cwmp__OptionStruct (32)
#endif

/* struct cwmp__QueuedTransferStruct has binding name 'cwmp__QueuedTransferStruct' for type 'cwmp:QueuedTransferStruct' */
#ifndef SOAP_TYPE_cwmp__QueuedTransferStruct
#define SOAP_TYPE_cwmp__QueuedTransferStruct (30)
#endif

/* struct cwmp__ParameterAttributeStruct has binding name 'cwmp__ParameterAttributeStruct' for type 'cwmp:ParameterAttributeStruct' */
#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (28)
#endif

/* struct AccessList has binding name 'AccessList' for type 'xsd:string' */
#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (26)
#endif

/* struct cwmp__SetParameterAttributesStruct has binding name 'cwmp__SetParameterAttributesStruct' for type 'cwmp:SetParameterAttributesStruct' */
#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (23)
#endif

/* struct cwmp__ParameterInfoStruct has binding name 'cwmp__ParameterInfoStruct' for type 'cwmp:ParameterInfoStruct' */
#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (22)
#endif

/* struct cwmp__ParameterValueStruct has binding name 'cwmp__ParameterValueStruct' for type 'cwmp:ParameterValueStruct' */
#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (21)
#endif

/* struct cwmp__EventStruct has binding name 'cwmp__EventStruct' for type 'cwmp:EventStruct' */
#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (20)
#endif

/* struct cwmp__DeviceIdStruct has binding name 'cwmp__DeviceIdStruct' for type 'cwmp:DeviceIdStruct' */
#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (19)
#endif

/* struct cwmp__FaultStruct has binding name 'cwmp__FaultStruct' for type 'cwmp:FaultStruct' */
#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (17)
#endif

/* struct SOAP_ENC__base64 has binding name 'SOAP_ENC__base64' for type 'SOAP-ENC:base64' */
#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (143)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (142)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (136)
#endif

/* struct cwmp__InformResponse * has binding name 'PointerTocwmp__InformResponse' for type 'cwmp:InformResponse' */
#ifndef SOAP_TYPE_PointerTocwmp__InformResponse
#define SOAP_TYPE_PointerTocwmp__InformResponse (132)
#endif

/* struct cwmp__ArgStruct ** has binding name 'PointerToPointerTocwmp__ArgStruct' for type 'cwmp:ArgStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__ArgStruct
#define SOAP_TYPE_PointerToPointerTocwmp__ArgStruct (127)
#endif

/* struct cwmp__ArgStruct * has binding name 'PointerTocwmp__ArgStruct' for type 'cwmp:ArgStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__ArgStruct
#define SOAP_TYPE_PointerTocwmp__ArgStruct (126)
#endif

/* struct cwmp__OptionStruct ** has binding name 'PointerToPointerTocwmp__OptionStruct' for type 'cwmp:OptionStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__OptionStruct
#define SOAP_TYPE_PointerToPointerTocwmp__OptionStruct (125)
#endif

/* struct cwmp__OptionStruct * has binding name 'PointerTocwmp__OptionStruct' for type 'cwmp:OptionStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__OptionStruct
#define SOAP_TYPE_PointerTocwmp__OptionStruct (124)
#endif

/* struct SOAP_ENC__base64 * has binding name 'PointerToSOAP_ENC__base64' for type 'SOAP-ENC:base64' */
#ifndef SOAP_TYPE_PointerToSOAP_ENC__base64
#define SOAP_TYPE_PointerToSOAP_ENC__base64 (123)
#endif

/* struct cwmp__QueuedTransferStruct ** has binding name 'PointerToPointerTocwmp__QueuedTransferStruct' for type 'cwmp:QueuedTransferStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__QueuedTransferStruct
#define SOAP_TYPE_PointerToPointerTocwmp__QueuedTransferStruct (122)
#endif

/* struct cwmp__QueuedTransferStruct * has binding name 'PointerTocwmp__QueuedTransferStruct' for type 'cwmp:QueuedTransferStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__QueuedTransferStruct
#define SOAP_TYPE_PointerTocwmp__QueuedTransferStruct (121)
#endif

/* struct cwmp__ParameterAttributeStruct ** has binding name 'PointerToPointerTocwmp__ParameterAttributeStruct' for type 'cwmp:ParameterAttributeStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__ParameterAttributeStruct
#define SOAP_TYPE_PointerToPointerTocwmp__ParameterAttributeStruct (120)
#endif

/* struct cwmp__ParameterAttributeStruct * has binding name 'PointerTocwmp__ParameterAttributeStruct' for type 'cwmp:ParameterAttributeStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__ParameterAttributeStruct
#define SOAP_TYPE_PointerTocwmp__ParameterAttributeStruct (119)
#endif

/* struct cwmp__SetParameterAttributesStruct ** has binding name 'PointerToPointerTocwmp__SetParameterAttributesStruct' for type 'cwmp:SetParameterAttributesStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__SetParameterAttributesStruct
#define SOAP_TYPE_PointerToPointerTocwmp__SetParameterAttributesStruct (118)
#endif

/* struct cwmp__SetParameterAttributesStruct * has binding name 'PointerTocwmp__SetParameterAttributesStruct' for type 'cwmp:SetParameterAttributesStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__SetParameterAttributesStruct
#define SOAP_TYPE_PointerTocwmp__SetParameterAttributesStruct (117)
#endif

/* struct cwmp__ParameterInfoStruct ** has binding name 'PointerToPointerTocwmp__ParameterInfoStruct' for type 'cwmp:ParameterInfoStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__ParameterInfoStruct
#define SOAP_TYPE_PointerToPointerTocwmp__ParameterInfoStruct (116)
#endif

/* struct cwmp__ParameterInfoStruct * has binding name 'PointerTocwmp__ParameterInfoStruct' for type 'cwmp:ParameterInfoStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__ParameterInfoStruct
#define SOAP_TYPE_PointerTocwmp__ParameterInfoStruct (115)
#endif

/* struct cwmp__ParameterValueStruct ** has binding name 'PointerToPointerTocwmp__ParameterValueStruct' for type 'cwmp:ParameterValueStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__ParameterValueStruct
#define SOAP_TYPE_PointerToPointerTocwmp__ParameterValueStruct (114)
#endif

/* struct cwmp__ParameterValueStruct * has binding name 'PointerTocwmp__ParameterValueStruct' for type 'cwmp:ParameterValueStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__ParameterValueStruct
#define SOAP_TYPE_PointerTocwmp__ParameterValueStruct (113)
#endif

/* struct cwmp__EventStruct ** has binding name 'PointerToPointerTocwmp__EventStruct' for type 'cwmp:EventStruct' */
#ifndef SOAP_TYPE_PointerToPointerTocwmp__EventStruct
#define SOAP_TYPE_PointerToPointerTocwmp__EventStruct (112)
#endif

/* struct cwmp__EventStruct * has binding name 'PointerTocwmp__EventStruct' for type 'cwmp:EventStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__EventStruct
#define SOAP_TYPE_PointerTocwmp__EventStruct (111)
#endif

/* struct FileTypeArg * has binding name 'PointerToFileTypeArg' for type 'cwmp:ArgStruct' */
#ifndef SOAP_TYPE_PointerToFileTypeArg
#define SOAP_TYPE_PointerToFileTypeArg (109)
#endif

/* struct cwmp__FaultStruct * has binding name 'PointerTocwmp__FaultStruct' for type 'cwmp:FaultStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__FaultStruct
#define SOAP_TYPE_PointerTocwmp__FaultStruct (103)
#endif

/* struct EventList * has binding name 'PointerToEventList' for type 'cwmp:EventStruct' */
#ifndef SOAP_TYPE_PointerToEventList
#define SOAP_TYPE_PointerToEventList (100)
#endif

/* struct cwmp__DeviceIdStruct * has binding name 'PointerTocwmp__DeviceIdStruct' for type 'cwmp:DeviceIdStruct' */
#ifndef SOAP_TYPE_PointerTocwmp__DeviceIdStruct
#define SOAP_TYPE_PointerTocwmp__DeviceIdStruct (98)
#endif

/* struct OptionList * has binding name 'PointerToOptionList' for type 'cwmp:OptionStruct' */
#ifndef SOAP_TYPE_PointerToOptionList
#define SOAP_TYPE_PointerToOptionList (91)
#endif

/* struct VoucherList * has binding name 'PointerToVoucherList' for type 'SOAP-ENC:base64' */
#ifndef SOAP_TYPE_PointerToVoucherList
#define SOAP_TYPE_PointerToVoucherList (86)
#endif

/* struct TransferList * has binding name 'PointerToTransferList' for type 'cwmp:QueuedTransferStruct' */
#ifndef SOAP_TYPE_PointerToTransferList
#define SOAP_TYPE_PointerToTransferList (81)
#endif

/* struct ParameterAttributeList * has binding name 'PointerToParameterAttributeList' for type 'cwmp:ParameterAttributeStruct' */
#ifndef SOAP_TYPE_PointerToParameterAttributeList
#define SOAP_TYPE_PointerToParameterAttributeList (66)
#endif

/* struct SetParameterAttributesList * has binding name 'PointerToSetParameterAttributesList' for type 'cwmp:SetParameterAttributesStruct' */
#ifndef SOAP_TYPE_PointerToSetParameterAttributesList
#define SOAP_TYPE_PointerToSetParameterAttributesList (61)
#endif

/* struct ParameterInfoList * has binding name 'PointerToParameterInfoList' for type 'cwmp:ParameterInfoStruct' */
#ifndef SOAP_TYPE_PointerToParameterInfoList
#define SOAP_TYPE_PointerToParameterInfoList (58)
#endif

/* struct ParameterNames * has binding name 'PointerToParameterNames' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerToParameterNames
#define SOAP_TYPE_PointerToParameterNames (53)
#endif

/* struct ParameterValueList * has binding name 'PointerToParameterValueList' for type 'cwmp:ParameterValueStruct' */
#ifndef SOAP_TYPE_PointerToParameterValueList
#define SOAP_TYPE_PointerToParameterValueList (48)
#endif

/* struct MethodList * has binding name 'PointerToMethodList' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerToMethodList
#define SOAP_TYPE_PointerToMethodList (45)
#endif

/* struct _cwmp__Fault_SetParameterValuesFault * has binding name 'PointerTo_cwmp__Fault_SetParameterValuesFault' for type '' */
#ifndef SOAP_TYPE_PointerTo_cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE_PointerTo_cwmp__Fault_SetParameterValuesFault (41)
#endif

/* time_t * has binding name 'PointerTodateTime' for type 'xsd:dateTime' */
#ifndef SOAP_TYPE_PointerTodateTime
#define SOAP_TYPE_PointerTodateTime (36)
#endif

/* struct AccessList * has binding name 'PointerToAccessList' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerToAccessList
#define SOAP_TYPE_PointerToAccessList (27)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (24)
#endif

/* cwmp__ObjectNameType has binding name 'cwmp__ObjectNameType' for type 'cwmp:ObjectNameType' */
#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (16)
#endif

/* cwmp__CommandKeyType has binding name 'cwmp__CommandKeyType' for type 'cwmp:CommandKeyType' */
#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (15)
#endif

/* cwmp__ParameterKeyType has binding name 'cwmp__ParameterKeyType' for type 'cwmp:ParameterKeyType' */
#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (14)
#endif

/* cwmp__FaultCodeType has binding name 'cwmp__FaultCodeType' for type 'cwmp:FaultCodeType' */
#ifndef SOAP_TYPE_cwmp__FaultCodeType
#define SOAP_TYPE_cwmp__FaultCodeType (13)
#endif

/* xsd__anySimpleType has binding name 'xsd__anySimpleType' for type 'xsd:anySimpleType' */
#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (12)
#endif

/* unsigned char * has binding name 'PointerTounsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct cwmp__DeviceIdStruct *DeviceId, struct EventList *Event, unsigned int MaxEnvelopes, time_t CurrentTime, unsigned int RetryCount, struct ParameterValueList *ParameterList, struct cwmp__InformResponse *response);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'cwmp__Inform' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 cwmp__Inform(struct soap*, struct cwmp__DeviceIdStruct *DeviceId, struct EventList *Event, unsigned int MaxEnvelopes, time_t CurrentTime, unsigned int RetryCount, struct ParameterValueList *ParameterList, struct cwmp__InformResponse *response);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
